### ISSUE TITLE
tdb.lock causes errors when restating docker container

### ISSUE THREAD

**Issue by niva83** [stain/jena-docker#47]
@stain ,

I am running jena-fuseki container on a linux server. 
Anytime when I restart the container I get an error message:
```bash
fuseki             | [2020-10-01 09:17:17] Server     ERROR Exception in initialization: caught: Process ID 9 can't open database at location /fuseki/databases/ontologies/ because it is already locked by the process with PID 10. TDB databases do not permit concurrent usage across JVMs so in order to prevent possible data corruption you cannot open this location from the JVM that does not own the lock for the dataset
```

Accordingly, there are `tdb.lock` files in `system` and `databases\ontologies` folders.

The only workaround I found for restarting the container withour any errors is to manually delete `tdb.lock` files.
This is a bit impractical, especially if I am going to have more than one database and multiple admins of our dockers.

Is there a solution that can prevent `tdb.lock` to cause errors in jena-fuseki container restarts?

**Comment by niva83** [comment]
I figure out temporary solution, using `command` in `docker-compose.yml`:

```
version: "3.7"

services:
  fuseki:
    container_name: skosmos-fuseki
    image: stain/jena-fuseki
    environment:
      - ADMIN_PASSWORD=${FUSEKI_PASS}
      - JVM_ARGS=-Xmx2g
    ports:
      - 3030:3030
    volumes:
      - ./fuseki_data:/fuseki
    command: bash -c "cd .. && find .. -name \tdb.lock -type f -delete &&  ./jena-fuseki/fuseki-server"
```

with the command part, anytime the container is restarted it auto-deletes `tdb.lock` files.
