### ISSUE TITLE
Dataset creation isn't working with 4.0.0 container

### ISSUE THREAD

**Issue by rmeissn** [stain/jena-docker#60]
I've used this config to bring up my fuseki container:
```
fuseki:
    image: stain/jena-fuseki:4.0.0
    network_mode: bridge
    expose:
      - 3030
    volumes:
      - db-data:/fuseki:rw
    env_file: .env
    environment:
      - FUSEKI_DATASET_1=test
      - FUSEKI_DATASET_2=test2
```
and included `ADMIN_PASSWORD=1234567890` in the .env file and also specified `db-data` as a named volume.

When the container is started, the webpage shows no created datasets and `docker logs` shows no warnings or errors.
