### ISSUE TITLE
4.8.0 - Process ID 8 can't open database at location /fuseki/system/ because it is already locked by the process with PID 7.

### ISSUE THREAD

**Issue by CN734539** [stain/jena-docker#80]
When building a fresh container with `docker-compose build --no-cache` then `docker-compose up` I receive the 
Error Message:

```
[+] Running 1/1
 ✔ Container recipekg-web-1  Recreated                                                                                                             0.2s
Attaching to web-1
web-1  | Waiting for Fuseki to finish starting up...
web-1  | 16:47:27 INFO  Server          :: Apache Jena Fuseki 4.8.0
web-1  | 16:47:27 INFO  Config          :: FUSEKI_HOME=/jena-fuseki
web-1  | 16:47:27 INFO  Config          :: FUSEKI_BASE=/fuseki
web-1  | 16:47:27 INFO  Config          :: Shiro file: file:///fuseki/shiro.ini
web-1  | 16:47:27 INFO  Config          :: Load configuration: file:///fuseki/configuration/RecipeKG.ttl
web-1  | 16:47:28 ERROR Server          :: Exception in initialization: Process ID 8 can't open database at location /fuseki/system/ because it is already locked by the process with PID 7. TDB databases do not permit concurrent usage across JVMs so in order to prevent possible data corruption you cannot open this location from the JVM that does not own the lock for the dataset
web-1  | 16:47:28 WARN  WebAppContext   :: Failed startup of context o.e.j.w.WebAppContext@48eaf42f{Apache Jena Fuseki Server,/,file:///jena-fuseki/webapp/,UNAVAILABLE}
web-1  | org.apache.jena.tdb.TDBException: Process ID 8 can't open database at location /fuseki/system/ because it is already locked by the process with PID 7. TDB databases do not permit concurrent usage across JVMs so in order to prevent possible data corruption you cannot open this location from the JVM that does not own the lock for the dataset
```

Dockerfile:
```
FROM stain/jena-fuseki:4.8.0

COPY RecipeKG/Data/Rdf-Data /staging
RUN /jena-fuseki/tdbloader --loc=RecipeKG /staging/1.ttl /staging/2.ttl /staging/3.ttl /staging/4.ttl /staging/5.ttl /staging/6.ttl /staging/7.ttl /staging/8.ttl

```

docker-compose.yml:
```

services:
  web:
    # image: stain/jena-fuseki
    build: .
    restart: always
    networks:
      - web
      - default
    expose:
      - "80"
      - "3030"
    volumes:
      - "./RecipeKG/Data/Rdf-Data/:/staging"
      - "./data:/fuseki"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.port=3030"
      - "traefik.http.routers.recipekg.rule=Host(`xxx.xxx.xxx`)"
      - "traefik.http.routers.recipekg.entrypoints=websecure"
      - "traefik.http.routers.recipekg.tls=true"
      - "traefik.http.routers.recipekg.middlewares=secHeadersMW@file"
      - "traefik.http.services.recipekg.loadbalancer.server.port=3030"


networks:
  web:
    external: true
```
